### ISSUE TITLE
node -v v0.8.16 utf encoding issue

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/not-impressed#4]
buffer.js:434
      throw new Error('Unknown encoding');
            ^
Error: Unknown encoding
    at Buffer.toString (buffer.js:434:13)
    at Object.fs.readFileSync (fs.js:236:33)
    at Object.readFileSync (/home/skawtus/workspace/not-impressed/node_modules/jsonfile/index.js:32:26)
    at Object.<anonymous> (/home/skawtus/workspace/not-impressed/app.js:5:21)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)

**Comment by scottleedavis** [comment]
adding support for node versions 0.8 & 0.9
