### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined when using license_finder

### ISSUE THREAD

**Issue by skylarhiebert** [scottleedavis/not-impressed#7]
The following error was created when running ni at the command line with the attached .ni.json file. It appears to happen immediately after or during the license_finder execution. The license_finder utility can be run independently with no failure. It does appear that license_finder output is fully run and the error occurs after license_finder command completes.

```
/usr/local/lib/node_modules/not-impressed/lib/parsers.js:16
			        version: ns[1].trim(),
			                      ^

TypeError: Cannot read property 'trim' of undefined
    at /usr/local/lib/node_modules/not-impressed/lib/parsers.js:16:26
    at arrayEach (/usr/local/lib/node_modules/not-impressed/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/not-impressed/node_modules/lodash/index.js:3345:13)
    at license_finder (/usr/local/lib/node_modules/not-impressed/lib/parsers.js:12:6)
    at Object.strap (/usr/local/lib/node_modules/not-impressed/lib/parsers.js:83:25)
    at strap (/usr/local/lib/node_modules/not-impressed/lib/parse.js:8:20)
    at /usr/local/lib/node_modules/not-impressed/lib/parse.js:14:21
    at arrayEach (/usr/local/lib/node_modules/not-impressed/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/not-impressed/node_modules/lodash/index.js:3345:13)
    at Object.parse [as run] (/usr/local/lib/node_modules/not-impressed/lib/parse.js:13:7)
```

```
{
  "Report": "Not Impressed",
  "output": "results.json",
  "build": {
    "maven": {
      "pattern": "pom.xml",
      "command": "mvn package; rm -f target; ln -s dist target"
    }
  },
  "scan": {
    "debug": true,
    "license": {
      "command": "license_finder"
    }
  }
}
```

**Comment by scottleedavis** [comment]
@skylarhiebert ni version released 0.2.0 has a fix for this issue.  please update and confirm.
